name: Code checks

on:
  push:
    branches: [ master ]
  pull-request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/install-python@v2
        with: 
          python-version: 3.11.2
      - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
